import '../models/seafood_models.dart';

class MockApiService {
  static final List<Category> categories = [
    Category(id: '1', name: 'Fish', iconPath: 'assets/icons/fish.svg'),
    Category(id: '2', name: 'Prawns', iconPath: 'assets/icons/prawn.svg'),
    Category(id: '3', name: 'Crabs', iconPath: 'assets/icons/crab.svg'),
    Category(id: '4', name: 'Shellfish', iconPath: 'assets/icons/shell.svg'),
    Category(id: '5', name: 'Ready-to-Cook', iconPath: 'assets/icons/cooking.svg'),
  ];

  static final List<SeafoodProduct> products = [
    SeafoodProduct(
      id: 'p1',
      name: 'Fresh Atlantic Salmon',
      description: 'Premium quality Atlantic Salmon, rich in Omega-3. Perfect for grilling or pan-searing.',
      price: 25.0,
      categoryId: '1',
      images: ['https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800'],
      rating: 4.8,
      reviewsCount: 124,
      origin: 'Norway',
      freshnessInfo: 'Caught 12 hours ago',
      weightOptions: ['500g', '1kg', '2kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.9, '2kg': 3.7},
      isFeatured: true,
    ),
    SeafoodProduct(
      id: 'p6',
      name: 'King Fish (Surmai)',
      description: 'The king of fish! Meaty and delicious, perfect for traditional curry or shallow fry.',
      price: 28.0,
      categoryId: '1',
      images: ['https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800'],
      rating: 4.9,
      reviewsCount: 210,
      origin: 'Arabian Sea',
      freshnessInfo: 'Fresh catch of the day',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.9},
      isFeatured: true,
    ),
    SeafoodProduct(
      id: 'p7',
      name: 'Rohu (Cleaned)',
      description: 'Freshwater Rohu, perfectly cleaned and sliced. Ideal for fish fry or curry.',
      price: 12.0,
      categoryId: '1',
      images: ['https://images.unsplash.com/photo-1551248429-40975aa49f61?w=800'],
      rating: 4.5,
      reviewsCount: 156,
      origin: 'Local Rivers',
      freshnessInfo: 'Farm fresh',
      weightOptions: ['1kg', '2kg'],
      weightMultipliers: {'1kg': 1.0, '2kg': 1.9},
    ),
    SeafoodProduct(
      id: 'p2',
      name: 'Tiger Prawns (Jumbo)',
      description: 'Large, juicy Tiger Prawns. Great for curries and BBQ.',
      price: 18.0,
      categoryId: '2',
      images: ['https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800'],
      rating: 4.9,
      reviewsCount: 89,
      origin: 'Arabian Sea',
      freshnessInfo: 'Flash frozen at sea',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.8},
      isDailyDeal: true,
      discountPrice: 15.0,
    ),
    SeafoodProduct(
      id: 'p8',
      name: 'White Prawns (Large)',
      description: 'Sweet and tender white prawns, deveined and ready to cook.',
      price: 15.0,
      categoryId: '2',
      images: ['https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=800'],
      rating: 4.7,
      reviewsCount: 112,
      origin: 'Coastal Farms',
      freshnessInfo: 'Peeled & Deveined',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.9},
    ),
    SeafoodProduct(
      id: 'p3',
      name: 'Mud Crabs',
      description: 'Sweet and meaty mud crabs, ideal for Singaporean chili crab style.',
      price: 30.0,
      categoryId: '3',
      images: ['https://images.unsplash.com/photo-1550951160-844977465918?w=800'],
      rating: 4.7,
      reviewsCount: 56,
      origin: 'Local Mangroves',
      freshnessInfo: 'Live arrival guaranteed',
      weightOptions: ['1kg', '2kg'],
      weightMultipliers: {'1kg': 1.0, '2kg': 1.85},
    ),
    SeafoodProduct(
      id: 'p9',
      name: 'Blue Swimmer Crabs',
      description: 'Delicate and sweet meat, perfect for soups and salads.',
      price: 24.0,
      categoryId: '3',
      images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800'],
      rating: 4.6,
      reviewsCount: 42,
      origin: 'Coastal Waters',
      freshnessInfo: 'Chilled',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.8},
    ),
    SeafoodProduct(
      id: 'p4',
      name: 'Black Pomfret',
      description: 'Fresh Black Pomfret, cleaned and ready for frying.',
      price: 22.0,
      categoryId: '1',
      images: ['https://images.unsplash.com/photo-1534341901861-f09c06368022?w=800'],
      rating: 4.6,
      reviewsCount: 45,
      origin: 'Indian Ocean',
      freshnessInfo: 'Fresh daily from harbor',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.9},
      isFeatured: true,
    ),
    SeafoodProduct(
      id: 'p5',
      name: 'Scallops in Shell',
      description: 'Delicious sea scallops, perfect with garlic butter.',
      price: 35.0,
      categoryId: '4',
      images: ['https://images.unsplash.com/photo-1604543265050-ec4839556847?w=800'],
      rating: 4.9,
      reviewsCount: 32,
      origin: 'Hokkaido',
      freshnessInfo: 'Hand-picked today',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.95},
    ),
    SeafoodProduct(
      id: 'p10',
      name: 'Lemon Garlic Marinated Salmon',
      description: 'Ready-to-cook salmon fillets marinated with fresh lemon and garlic.',
      price: 28.0,
      categoryId: '5',
      images: ['https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800'],
      rating: 4.8,
      reviewsCount: 78,
      origin: 'Store Special',
      freshnessInfo: 'Marinated 2h ago',
      weightOptions: ['500g'],
      weightMultipliers: {'500g': 1.0},
      isDailyDeal: true,
      discountPrice: 22.0,
    ),
    SeafoodProduct(
      id: 'p11',
      name: 'Spicy Fish Tikka',
      description: 'Traditional spicy marinade on tender fish cubes. Ready for your grill!',
      price: 16.0,
      categoryId: '5',
      images: ['https://images.unsplash.com/photo-1594041680534-e8c8cdebd679?w=800'],
      rating: 4.6,
      reviewsCount: 95,
      origin: 'Authentic Recipe',
      freshnessInfo: 'Spiced fresh',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.8},
    ),
    SeafoodProduct(
      id: 'p12',
      name: 'California Dungeness Crab',
      description: 'The legendary taste of San Francisco! Sweet, tender, and meaty Dungeness crab, caught fresh from the cold Pacific waters.',
      price: 45.0,
      categoryId: '3',
      images: ['https://images.unsplash.com/photo-1590424753042-4914d334dd72?w=800'],
      rating: 4.9,
      reviewsCount: 320,
      origin: 'California, USA',
      freshnessInfo: 'Fresh from Bay Area',
      weightOptions: ['1kg', '2kg'],
      weightMultipliers: {'1kg': 1.0, '2kg': 1.9},
      isFeatured: true,
    ),
    SeafoodProduct(
      id: 'p13',
      name: 'Santa Barbara Sea Urchin (Uni)',
      description: 'World-renowned creamy and buttery Uni. A true delicacy for sushi lovers, harvested from the kelp forests of Santa Barbara.',
      price: 65.0,
      categoryId: '4',
      images: ['https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800'],
      rating: 5.0,
      reviewsCount: 145,
      origin: 'California, USA',
      freshnessInfo: 'Hand-picked today',
      weightOptions: ['100g (Tray)', '200g (Tray)'],
      weightMultipliers: {'100g (Tray)': 1.0, '200g (Tray)': 1.8},
      isFeatured: true,
    ),
    SeafoodProduct(
      id: 'p14',
      name: 'Pacific Spiny Lobster',
      description: 'The pride of Southern California. Unlike Maine lobsters, these are known for their massive, sweet tail meat.',
      price: 55.0,
      categoryId: '3',
      images: ['https://images.unsplash.com/photo-1541014741259-de529411b96a?w=800'],
      rating: 4.8,
      reviewsCount: 92,
      origin: 'California, USA',
      freshnessInfo: 'Live from SoCal',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.85},
    ),
    SeafoodProduct(
      id: 'p15',
      name: 'California Rockfish',
      description: 'A versatile local favorite. Perfect for authentic California-style fish tacos or pan-searing with lemon butter.',
      price: 18.0,
      categoryId: '1',
      images: ['https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800'],
      rating: 4.7,
      reviewsCount: 188,
      origin: 'California, USA',
      freshnessInfo: 'Wild caught',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.9},
    ),
    SeafoodProduct(
      id: 'p16',
      name: 'Monterey Bay Spot Prawns',
      description: 'Highly seasonal and incredibly sweet prawns from the deep waters of Monterey Bay.',
      price: 38.0,
      categoryId: '2',
      images: ['https://images.unsplash.com/photo-1565689157206-0fddef7589a2?w=800'],
      rating: 4.9,
      reviewsCount: 64,
      origin: 'California, USA',
      freshnessInfo: 'Limited Catch',
      weightOptions: ['500g', '1kg'],
      weightMultipliers: {'500g': 1.0, '1kg': 1.8},
    ),
  ];

  Future<List<SeafoodProduct>> getFeaturedProducts() async {
    await Future.delayed(const Duration(milliseconds: 800));
    return products.where((p) => p.isFeatured).toList();
  }

  Future<List<SeafoodProduct>> getDailyDeals() async {
    await Future.delayed(const Duration(milliseconds: 800));
    return products.where((p) => p.isDailyDeal).toList();
  }

  Future<List<Category>> getCategories() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return categories;
  }

  Future<List<SeafoodProduct>> getProductsByCategory(String categoryId) async {
    await Future.delayed(const Duration(milliseconds: 800));
    return products.where((p) => p.categoryId == categoryId).toList();
  }

  Future<SeafoodProduct> getProductDetail(String productId) async {
    await Future.delayed(const Duration(milliseconds: 800));
    return products.firstWhere((p) => p.id == productId);
  }
}
